"""add vaults, categories, items, item versions

Revision ID: 0b222c33dfa7
Revises: 9c1b88a71907
Create Date: 2026-08-11 18:06:46.538275

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b222c33dfa7'
down_revision: Union[str, None] = '9c1b88a71907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaults',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vaults_owner_id', 'vaults', ['owner_id'], unique=False)
    op.create_table('categories',
    sa.Column('vault_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_vault_id', 'categories', ['vault_id'], unique=False)
    op.create_index('ix_categories_vault_name', 'categories', ['vault_id', 'name'], unique=False)
    op.create_table('vault_items',
    sa.Column('vault_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('document', 'note', 'financial', 'insurance', 'medical', 'legal', 'emergency', 'contact', 'digital_asset', name='item_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_encrypted', sa.Text(), nullable=False),
    sa.Column('masked_summary', sa.String(length=300), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vault_items_category_id', 'vault_items', ['category_id'], unique=False)
    op.create_index('ix_vault_items_title', 'vault_items', ['title'], unique=False)
    op.create_index('ix_vault_items_type', 'vault_items', ['item_type'], unique=False)
    op.create_index('ix_vault_items_vault_id', 'vault_items', ['vault_id'], unique=False)
    op.create_table('item_versions',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_encrypted', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['vault_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_item_versions_item_id', 'item_versions', ['item_id'], unique=False)
    op.create_index('ix_item_versions_version', 'item_versions', ['item_id', 'version_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_versions_version', table_name='item_versions')
    op.drop_index('ix_item_versions_item_id', table_name='item_versions')
    op.drop_table('item_versions')
    op.drop_index('ix_vault_items_vault_id', table_name='vault_items')
    op.drop_index('ix_vault_items_type', table_name='vault_items')
    op.drop_index('ix_vault_items_title', table_name='vault_items')
    op.drop_index('ix_vault_items_category_id', table_name='vault_items')
    op.drop_table('vault_items')
    op.drop_index('ix_categories_vault_name', table_name='categories')
    op.drop_index('ix_categories_vault_id', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_vaults_owner_id', table_name='vaults')
    op.drop_table('vaults')
    op.execute('DROP TYPE IF EXISTS item_type')
    # ### end Alembic commands ###
