"""add trusted contacts

Revision ID: 279525425d18
Revises: 0b222c33dfa7
Create Date: 2026-08-11 18:52:16.298667

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279525425d18'
down_revision: Union[str, None] = '0b222c33dfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_contacts',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', name='contact_status'), nullable=False),
    sa.Column('can_activate_emergency', sa.Boolean(), nullable=False),
    sa.Column('can_view_vaults', sa.Boolean(), nullable=False),
    sa.Column('access_grace_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'contact_id', name='uq_trusted_contacts_owner_contact')
    )
    op.create_index('ix_trusted_contacts_contact_id', 'trusted_contacts', ['contact_id'], unique=False)
    op.create_index('ix_trusted_contacts_owner_id', 'trusted_contacts', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trusted_contacts_owner_id', table_name='trusted_contacts')
    op.drop_index('ix_trusted_contacts_contact_id', table_name='trusted_contacts')
    op.drop_table('trusted_contacts')
    op.execute('DROP TYPE IF EXISTS contact_status')
    # ### end Alembic commands ###
