"""add otp verification tokens

Revision ID: 2a064b8c0def
Revises: d6f5c64bbda6
Create Date: 2026-08-18 14:53:23.763832

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a064b8c0def'
down_revision: Union[str, None] = 'd6f5c64bbda6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('otp_code', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('is_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_verification_tokens_expires', 'otp_verification_tokens', ['expires_at'], unique=False)
    op.create_index('ix_otp_verification_tokens_purpose', 'otp_verification_tokens', ['purpose'], unique=False)
    op.create_index('ix_otp_verification_tokens_user_id', 'otp_verification_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_otp_verification_tokens_user_id', table_name='otp_verification_tokens')
    op.drop_index('ix_otp_verification_tokens_purpose', table_name='otp_verification_tokens')
    op.drop_index('ix_otp_verification_tokens_expires', table_name='otp_verification_tokens')
    op.drop_table('otp_verification_tokens')
    # ### end Alembic commands ###
