"""add otp used_at

Revision ID: 88760b7269e0
Revises: 2a064b8c0def
Create Date: 2026-08-18 15:02:27.053530

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88760b7269e0'
down_revision: Union[str, None] = '2a064b8c0def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verification_tokens', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_verification_tokens', 'used_at')
    # ### end Alembic commands ###
