"""add emergencies

Revision ID: 95a2013ad1c7
Revises: 279525425d18
Create Date: 2026-08-11 19:35:56.734742

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a2013ad1c7'
down_revision: Union[str, None] = '279525425d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergencies',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('activated_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'escalated', 'resolved', 'cancelled', name='emergency_status'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('grace_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activated_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emergencies_activated_by', 'emergencies', ['activated_by'], unique=False)
    op.create_index('ix_emergencies_owner_id', 'emergencies', ['owner_id'], unique=False)
    op.create_index('ix_emergencies_status', 'emergencies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emergencies_status', table_name='emergencies')
    op.drop_index('ix_emergencies_owner_id', table_name='emergencies')
    op.drop_index('ix_emergencies_activated_by', table_name='emergencies')
    op.drop_table('emergencies')
    op.execute('DROP TYPE IF EXISTS emergency_status')
    # ### end Alembic commands ###
